config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :genes, only: [:show, :index], defaults: {format: 'html'} do
    resources :external_resources_genes, only: :index
  end
  resources :conditions, only: [:show, :index], defaults: {format: 'html'} do
    resources :external_resources_conditions, only: :index
  end
  resources :drugs, only: [:show, :index] do
    resources :external_resources_drugs, only: :index
  end
  resources :curations, only: :index
  resources :gene_dosage, only: :index, path: "/gene-dosage"
  resources :gene_disease_assertions, only: [:show, :index], path: "/gene-validity"
  resources :actionability_assertions, only: [:show, :index], path: "/actionability"
  resources :home, only: [:show, :index]
  resources :phenotypes, only: [:index]

  resources :affiliates, only: [:show, :index, :all] do
    member do
      get 'all'
    end
  end


  # Items that need to be secured
  authenticate :agent do
    resources :subscriptions
    resources :notes
    resources :dashboard, only: [:index]  #should only be registered agents
  end


  # TODO refine routes later, for now want routes for
  # disease, conditions, and phenotypes
  # resources :diseases
  resources :conditions
  # no phenotypes yet, but soon!
  # resources :phenotypes

  devise_for :agents

  root to: 'home#index'
end

app/views/shared/_actionability_detail.html.erb
<% # args: [actionability] structure to render, [gene] [disease] [index] which (:gene/:disease) the index is based on %>

<table class="table table-hover border-left table-condensed">
  <thead>
    <tr>
      <th class="col-sm-10 th-curation-group" colspan="2"><%= info_popover("actionability", "help") %></th>
      <th class="col-sm-2 text-center"></th>
      <th class="col-sm-1 text-center"></th>
    </tr>
  </thead>

  <thead class="thead-labels ">
    <tr>
      <th class="col-sm-5">Outcome/Intervention Pair</th>
      <th class="">Description</th>
      <th class="text-center col-sm-2">Date</th>
      <th class="text-center col-sm-1"></th>
    </tr>
  </thead>
  <tbody>
    <% if assertion = actionability.find { |a| a[index].include?(index_id) } %>
      <% assertion[:interventions].each do |i| %>
        <% scores = ActionabilityScore.labels_to_h(i[:scores]) %>
        <tr>
          <td>
            <strong><%= i[:label] %></strong>
          </td>
          <td class=" text-left">
            <dl class='dl-horizontal'> 
              <dt style='width:90px; font-weight:normal; margin-top:1px'><%= info_popover("actionability", "score", "Outcome") %></dt>
              <dd style='margin-left:100px'>Severity: <strong><%= scores[:severity] %></strong></dd>
              <dd style='margin-left:100px'>Likelihood: <strong><%= scores[:likelihood] %></strong></dd>
              <dt style='width:90px; font-weight:normal; margin-top:1px'><%= info_popover("actionability", "score", "Intervention") %></dt>
              <dd style='margin-left:100px'>Effectiveness: <strong><%= scores[:efficacy] %></strong></dd>
              <dd style='margin-left:100px'>Intervention: <strong><%= scores[:safety] %></strong></dd>
            </dl>
            
          </td>
          <td class=" text-center">
            <%= mdy_date(assertion[:date]) %>
          </td>
          <td class=" text-center">
            <a href="<%= assertion[:file] %>" target='file' class='btn btn-xs btn-success'>View report</a>
            
          </td>
        </tr>
      <% end %>
    <% end  %>
  </tbody>
</table>

app/views/shared/_actionability_detail_wide.html.erb
<% # args: [actionability] structure to render, [gene] [disease] [index] which (:gene/:disease) the index is based on %>
  <tbody>
    <% if assertion = actionability.find { |a| a[index].include?(index_id) } %>
        <tr>
          <td><%= info_popover("actionability", "help", "" ,"logo-inline") %></td>
          <td>
            <strong>View report for scoring details</strong>
          </td>

          <td class=" text-center">
          
          </td>
          <td class=" text-center">
            <%= mdy_date(assertion[:date]) %>
          </td>
          <td class=" text-center">
          <% 
            search_text = assertion[:label].split('-')
            if @gene.present? 
              search_gene = @gene.symbol
            elsif
              search_gene = gene.label
            end
          %>
          <a href="https://actionability.clinicalgenome.org/ac/?search=<%= URI.encode(search_text.first) %>%20<%= search_gene %>" target='file' class='btn btn-xs btn-success watchreportclick' title='Click Actionability Report'>View report</a>
          </td>
        </tr>
    <% end  %>
  </tbody>

app/views/shared/_agent_controls.html.erb
<% content_for :agent_controls do %>
  <div class="btn-group" role="group">
    <%= link_to dashboard_index_path, :class => "btn btn-default dropdown-toggle", :data => { :'toggle' => 'dropdown' }  do %>
      <i class="glyphicon glyphicon-th-list"></i> Your Dashboard <span class="caret"></span>
    <% end %>
    <ul class="dropdown-menu dropdown-menu-right">
      <li>
        <%= link_to dashboard_index_path, :class => ""  do %>
          <i class="glyphicon glyphicon-th-list"></i> View Your Dashboard
        <% end %>
      </li>
      <li>
        <%= link_to edit_agent_registration_path, :class => ""  do %>
          <i class="glyphicon glyphicon-user"></i> Manage Profile
        <% end %>
      </li>
      <li role="separator" class="divider"></li>
      <li>
        <%= link_to destroy_agent_session_path, :method => :delete, :class => ""  do %>
          <i class="glyphicon glyphicon-off text-danger"></i> Sign-out
        <% end %>
      </li>
    </ul>
  </div>
<% end %>

app/views/shared/_agent_links_show_views.html.erb
<% # KEEP THIS FILE IN CASE WE NEED TO DISPLAY TEXT WHY FOLLOW/SHARE ISN"T AVAIABLE %>

app/views/shared/_result_list_condition.erb
<div class='row margin-bottom-sm ADDCLASSIFCURATED' id='result_ADDIDHERE'>
  <div class='col-sm-8'>
    <h4 class='margin-top-none'><%= link_to condition.label, condition %></a></h4>
    <div>
      <%= condition.curie %> <span class='badge text-xs'>Condition</span>
    </div>
    
    <div class='text-sm text-muted'>
      <%= condition.synonym %>
    </div>
    
  </div>
  <%= entity_assertion_key condition %>
  <div class='col-sm-2 text-right text-tight text-sm text-muted'>
    <!--MOST RECENT CURATED DATE -->  <%= mdy_date(condition.last_curated) %>
  </div>

  <hr class='col-sm-12' />
</div>

app/views/shared/_result_list_curation.erb
<div class='row margin-bottom-sm' id='result_ADDIDHERE'>
<div class='col-sm-8'>
  <h4 class='margin-top-none'><%= link_to "ONTOLOGICAL CONDITION NAME", conditions_path %></a></h4>
  <div>
    <%= link_to conditions_path, conditions_path %> <span class='badge text-xs'>Gene</span>
  </div>
  
</div>
<div class='col-sm-2'>
	<div class='col-sm-3 padding-right-none'>
      <%= link_to image_tag("clinicalActionability-on.png", class: "img-responsive"), genes_path, class: "menu_icon" %>
    </div>
	<div class='col-sm-3 padding-right-none'>
      <%= link_to image_tag("clinicalValidity-on.png", class: "img-responsive"), genes_path, class: "menu_icon" %>
    </div>
	<div class='col-sm-3 padding-right-none'>
      <%= link_to image_tag("dosageSensitivity-on.png", class: "img-responsive"), genes_path, class: "menu_icon" %>
    </div>
	<div class='col-sm-3 padding-right-none'>
      <%= link_to image_tag("genomeResource-on.png", class: "img-responsive"), genes_path, class: "menu_icon" %>
    </div>
</div>
<div class='col-sm-2 text-right text-tight text-sm text-muted'>
</div>

<hr class='col-sm-12' />
</div>

app/views/shared/_result_list_drug.erb
<div class='row margin-bottom-sm ADDCLASSIFCURATED' id='result_ADDIDHERE'>
<div class='col-sm-8'>
  <h4 class='margin-top-none'><%= link_to d.label, d %></a></h4>
  <div>
    RXNORM:<%= d.curie %> <span class='badge text-xs'>Drug</span>
  </div>
  
  <!-- <div class='text-sm text-muted'>
       Synonyms go here
       </div> -->
  
</div> 
<div class='col-sm-2 hidden-xs'>
	<div class='col-sm-3 padding-right-none'>
      <%= link_to image_tag("clinicalActionability-off.png", class: "img-responsive"), d, class: "menu_icon" %>
    </div>
	<div class='col-sm-3 padding-right-none'>
      <%= link_to image_tag("clinicalValidity-off.png", class: "img-responsive"), d, class: "menu_icon" %>
    </div>
	<div class='col-sm-3 padding-right-none'>
      <%= link_to image_tag("dosageSensitivity-off.png", class: "img-responsive"), d, class: "menu_icon" %>
    </div>
</div>
<div class='col-sm-2 text-right text-tight text-sm text-muted'>
</div>

<hr class='col-sm-12' />
</div>

app/views/shared/_result_list_gene.erb
<% if(@genes) %>
  <div class='row margin-bottom-sm ADDCLASSIFCURATED' id='result_ADDIDHERE'>
  <div class='col-sm-8'>
    <h4 class='margin-top-none'><%= link_to gene.symbol, gene %></a></h4>
    <div>
      <%= link_to genes_path+"/"+gene.hgnc_id, genes_path+"/"+gene.hgnc_id %> <span class='badge text-xs'>Gene</span>
    </div>
    
    <div class='text-sm text-muted'>
      <%= gene.name ? gene.name : "NULL" %>
    </div>
    
  </div>
  <%= entity_assertion_key gene %>
  <div class='col-sm-2 text-right text-tight text-sm text-muted'>
    <%= mdy_date(gene.last_curated) %>
  </div>

  <hr class='col-sm-12' />
  </div>
<% end %>

app/views/shared/_splash_curated_facts.html.erb
<div class="row text-center margin-bottom-lg margin-top-lg">
  <div class="col-sm-12 margin-bottom-lg"><h2>Search the Knowledge Base by using the search box at the top of all pages.</h2>
</div>
</div>



<div class="row padding-top-xs">
          <div class="col-sm-3 col-xs-12 text-center"><div class="padding-left-sm padding-right-sm thumbnail shadow-glow ">
            <div class="col-sm-12 text-center"><%= link_to curations_path, :class => ""  do %><%= image_tag("home_curated_list.png", class: "img-responsive img-rounded") %><% end %></div><br clear="all">
            <%= link_to curations_path, class: "padding-none margin-none text-muted row" do %>
              <h5 class="col-sm-10 col-sm-offset-1 headingtight padding-none margin-top-none margin-bottom-md text-center">All ClinGen Curated Genes<div class='hidden-md hidden-xs'>&nbsp;</div></h5><small class="text-muted"></small>
            <% end %>
            </div></div>
          <div class="col-sm-3 col-xs-12 text-center"><div class="padding-left-sm padding-right-sm thumbnail shadow-glow ">
            <div class="col-sm-12 text-center"><%= link_to gene_disease_assertions_path, :class => ""  do %><%= image_tag("home_clinicalValidity.png", class: "img-responsive img-rounded") %><% end %></div><br clear="all">
              <%= link_to gene_disease_assertions_path, :class => "padding-none margin-none text-muted row"  do %><h5 class="col-sm-10 col-sm-offset-1 headingtight padding-none margin-top-none margin-bottom-md text-center">Gene-Disease Validity Curations</h5><small class="text-muted"></small><% end %>  

            </div></div>
          <div class="col-sm-3 col-xs-12 text-center"><div class="padding-left-sm padding-right-sm thumbnail shadow-glow ">
            <div class="col-sm-12 text-center"><%= link_to gene_dosage_index_path, :class => ""  do %><%= image_tag("home_dosage_sensitivity.png", class: "img-responsive img-rounded") %><% end %></div><br clear="all">
              <%= link_to gene_dosage_index_path, :class => "adding-none margin-none text-muted row"  do %><h5 class="col-sm-10 col-sm-offset-1 headingtight padding-none margin-top-none margin-bottom-md text-center">Dosage Sensitivity Curations</h5><small class="text-muted"></small><% end %>  

            </div></div>
          <div class="col-sm-3 col-xs-12 text-center"><div class="padding-left-sm padding-right-sm thumbnail shadow-glow ">
            <div class="col-sm-12 text-center"><%= link_to actionability_assertions_path, :class => ""  do %><%= image_tag("home_clinicalActionability.png", class: "img-responsive img-rounded") %><% end %></div><br clear="all">
              <%= link_to actionability_assertions_path, :class => "padding-none margin-none text-muted row"  do %><h5 class="col-sm-10 col-sm-offset-1 headingtight padding-none margin-top-none margin-bottom-md text-center">Clinical Actionability Curations</h5><small class="text-muted"></small><% end %>  

            </div></div>
          </div>

<div class="row padding-top-xs">
  <hr />
</div>
    <div class="col-sm-6">
      <div class="row padding-top-xs">
        <div class="col-sm-3"><%= image_tag("home_share.png", class: "img-responsive img-rounded") %></div>
        <div class="col-sm-8">
            <h4 class="">Contact ClinGen</h4>For questions related to ClinGen, please <a href="https://www.clinicalgenome.org/contact/">
                click here to contact ClinGen.
              </a>
        </div>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="row padding-top-xs">
          <div class="col-sm-3"><%= image_tag("home_follow.png", class: "img-responsive img-rounded") %></div>
          <div class="col-sm-8">
              <h4 class="">Follow ClinGen Curation Updates</h4><i>Coming Soon</i> - Receive email updates whenever genes/conditions of interest are curated by ClinGen.
            
          </div>
      </div>
    </div>

app/views/shared/_subscribable_entity_header.html.erb
<% if false %>
<% if agent_signed_in? %>
  <% if current_agent.subscribed_to?(entity) %>
    <%= link_to "unsubscribe", subscription_path(entity.curie), method: :delete, class: "btn btn-link pull-right margin-bottom-md" %>
  <% else %>
  <% end %>
  <%= link_to new_note_path(id: entity.curie), :method => :get, :class => "btn btn-link pull-right  margin-bottom-md"  do %>
    <i class="glyphicon glyphicon-edit text-success"></i>
    <span class="text-success"> Share information</span>
  <% end %>
<% else %>
  <%= link_to new_agent_registration_path, :method => :get, :class => "btn btn-link pull-right  margin-bottom-md"  do %>
    <i class="glyphicon glyphicon-edit text-success"></i>
    <span class="text-success"><span class=' hidden-xs'>Sign-in to</span> share information</span>
  <% end %>
<% end %>
<% end %>