config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :genes, only: [:show, :index], defaults: {format: 'html'} do
    resources :external_resources_genes, only: :index
  end
  resources :conditions, only: [:show, :index], defaults: {format: 'html'} do
    resources :external_resources_conditions, only: :index
  end
  resources :drugs, only: [:show, :index] do
    resources :external_resources_drugs, only: :index
  end
  resources :curations, only: :index
  resources :gene_dosage, only: :index, path: "/gene-dosage"
  resources :gene_disease_assertions, only: [:show, :index], path: "/gene-validity"
  resources :actionability_assertions, only: [:show, :index], path: "/actionability"
  resources :home, only: [:show, :index]
  resources :phenotypes, only: [:index]

  resources :affiliates, only: [:show, :index, :all] do
    member do
      get 'all'
    end
  end


  # Items that need to be secured
  authenticate :agent do
    resources :subscriptions
    resources :notes
    resources :dashboard, only: [:index]  #should only be registered agents
  end


  # TODO refine routes later, for now want routes for
  # disease, conditions, and phenotypes
  # resources :diseases
  resources :conditions
  # no phenotypes yet, but soon!
  # resources :phenotypes

  devise_for :agents

  root to: 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @term         = params[:term]
    @termGene     = params[:termGene]
    @termDisease  = params[:termDisease]
    expires_in 10.minutes, public: true

    if !@term
      @term = params[:'mainSearchCriteria.v.dn']
    end

    if !@termGene
      @termGene = params[:'mainSearchCriteria.v.dn']
    end

    ## Passes the term queries to analytics
    @analyticsDimension5  = @term
    @analyticsDimension7  = "KB Home - Index"

    respond_to do |format|

      format.html do

        if @term
          @genesFound = Gene.find_by_term(@term).order(num_curations: :desc)
          @genes = @genesFound.limit(20)
          @conditionsFound = Condition.find_by_term(@term).order(num_curations: :desc)
          @conditions = @conditionsFound.limit(20)
          @drugsFound = Drug.find_by_term(@term)
          @drugs = @drugsFound.limit(20)

          if @genes.size > 0
            @active_class = :genes
          elsif @conditions.size > 0
            @active_class = :conditions
          elsif @drugs.size > 0
            @active_class = :drugs
          else
            @active_class = :none
          end

        else
          redirect_back fallback_location: "https://www.clinicalgenome.org/curation-activities/"
        end

          redirect_to @genes.first if @genes && @genes.length == 1 && @conditions.length == 0
          redirect_to @conditions.first if @conditions && @conditions.length == 1 && @genes.length == 0

      end
      format.json do 
        # return formatted json for typeahead
        if @term
          search_term = @term.upcase
          @genes = Gene.all(:g).where("g.search_label contains {term}")
                     .params(term: search_term).limit(10).to_a
          @conditions = Condition.all(:c).where("c.search_label contains {term}")
                          .params(term: search_term).limit(10).to_a
          @drugs = Drug.all(:d).where("d.search_label contains {term}")
                     .params(term: search_term).limit(10).to_a
          terms = @genes + @conditions + @drugs
          @result = terms.map { |t| {label: "#{t.label} (#{t.curie.tr '_', ':'})", url: url_for(t)} }
          render json: @result
        end
        if @termGene
          search_term = @termGene.upcase
          @genes = Gene.all(:g).where("g.search_label contains {term}")
                     .params(term: search_term).limit(10).to_a
          terms = @genes 
          @result = terms.map { |t| {label: "#{t.label} (#{t.curie.tr '_', ':'})", url: url_for(t)} }
          render json: @result
        end
        if @termDisease
          search_term = @termDisease.upcase
          @conditions = Condition.all(:c).where("c.search_label contains {term}")
                          .params(term: search_term).limit(10).to_a
          terms = @conditions 
          @result = terms.map { |t| {label: "#{t.label} (#{t.curie.tr '_', ':'})", url: url_for(t)} }
          render json: @result
        end
        if @termOrig
          search_term = @term.upcase
          @genes = Gene.all(:g).where("g.search_label contains {term}")
                     .params(term: search_term).limit(10).to_a
          @conditions = Condition.all(:c).where("c.search_label contains {term}")
                          .params(term: search_term).limit(10).to_a
          @drugs = Drug.all(:d).where("d.search_label contains {term}")
                     .params(term: search_term).limit(10).to_a
          terms = @genes + @conditions + @drugs
          @result = terms.map { |t| {label: "#{t.label} (#{t.curie.tr '_', ':'})", url: url_for(t)} }
          render json: @result
        end
      end
    end
  end

end


	

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_condition_results.html.erb
<% @conditions.each do |c| %>
  <%= render 'shared/result_list_condition', condition: c %>
<% end %>

app/views/home/_drug_results.html.erb
<% @drugs.each do |d| %>
    <%= render 'shared/result_list_drug', d: d %>
<% end %>

app/views/home/_gene_results.html.erb
<% @genes.each do |g| %>
  <%= render 'shared/result_list_gene', gene: g %>
<% end %>

app/views/home/_no_results.html.erb
<div class="col-sm-12">
	<div class="well text-center">
		<strong><%= @term %></strong> wasn't a match in our system.  Please try a different or choose one of the tabs above to filter the results.
	</div>
</div>

app/views/home/_search_results.html.erb
<div class="container">
  <%= render 'gene_results' %>
</div>

app/views/home/index.html.erb
<div id="home_index" class="container">

<% if(@term) %>
  <h2 class="margin-bottom-md"> <%= @term %> Results</h2>
  <%
    # Just some notes...
    # The "active" class set in the tabs and tab-content is what activates
    # the tabs that you want.  SO, just start with genes and go through the list.
    # My thought is to always keep the tabs (even if not matches) but always 
    # activate the first tab with results when reading from left to right.
  %>

  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="<%= 'active' if @active_class == :genes %>">
    	<a href="#gene_results" aria-controls="gene_results" role="tab" data-toggle="tab">Genes <span class="badge hidden-xs"><%= @genesFound.size %> Matches</span></a>
    </li>
    <li role="presentation" class="<%= 'active' if @active_class == :conditions %>">
    	<a href="#condition_results" aria-controls="condition_results" role="tab" data-toggle="tab">Conditions <span class="badge hidden-xs"><%= @conditionsFound.size %> Matches</span></a>
    </li>
    <li role="presentation" class="<%= 'active' if @active_class == :drugs %>">
    	<a href="#drug_results" aria-controls="drug_results" role="tab" data-toggle="tab">Drugs <span class="badge hidden-xs"><%= @drugsFound.size %> Matches</span></a>
    </li>
  </ul>


  <div class="tab-content">
    <% if @genesFound.size == 0 && @conditionsFound.size == 0 && @drugsFound.size == 0 %>
    <div role="tabpanel" class="tab-pane active" id="no_results">
      <div class="padding-top-md">
        <%= render "no_results" %>
      </div>
    </div>
    <% end %>
    <div role="tabpanel" class="tab-pane <%= 'active' if @active_class == :genes %>" id="gene_results">
      <div class="padding-top-md">
      <% if @genes.size == 0 %>
      <%= render "no_results" %>
      <% else %>
      <%= render "gene_results" %>
      <!-- START IF - only show this if more then X are needed -->
      <% if @genesFound.size > 20 %>
      <div class="col-sm-4 col-sm-offset-4">
        <%= link_to "Additional Gene Matches", genes_path(page: 2, term: @term), class: 'btn btn-primary btn-block' %>
      </div>
      <% end %>
      <!-- END IF -->

      <% end %>
      </div>
    </div>
    <div role="tabpanel" class="tab-pane <%= 'active' if @active_class == :conditions %>" id="condition_results">
      <div class="padding-top-md">
      <% if @conditions.size == 0 %>
      <%= render "no_results" %>
      <% else %>
      <%= render "condition_results" %>
      <!-- START IF - only show this if more then X are needed -->
      <% if @conditionsFound.size > 20 %>
      <div class="col-sm-4 col-sm-offset-4">
        <%= link_to "Additional Condition Matches", conditions_path(page: 2, term: @term), class: 'btn btn-primary btn-block' %>
      </div>
      <% end %>
      <!-- END IF -->
      <% end %>
    	</div>
    </div>
    <div role="tabpanel" class="tab-pane <%= 'active' if @active_class == :drugs %>" id="drug_results">
      <div class="padding-top-md">
      <% if @drugs.size == 0 %>
      <%= render "no_results" %>
      <% else %>
      <%= render "drug_results" %>
      <!-- START IF - only show this if more then X are needed -->
      <% if @drugsFound.size > 20 %>
      <div class="col-sm-4 col-sm-offset-4">
        <%= link_to "Additional Drug Matches", drugs_path(page: 2, term: @term), class: 'btn btn-primary btn-block' %>
      </div>
      <% end %>
      <!-- END IF -->
      <% end %>	
      </div>
    </div>
  </div>
    
<% else %>
    <%= render "shared/splash_curated_facts" %>
<% end %>    
  

</div>