config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :genes, only: [:show, :index], defaults: {format: 'html'} do
    resources :external_resources_genes, only: :index
  end
  resources :conditions, only: [:show, :index], defaults: {format: 'html'} do
    resources :external_resources_conditions, only: :index
  end
  resources :drugs, only: [:show, :index] do
    resources :external_resources_drugs, only: :index
  end
  resources :curations, only: :index
  resources :gene_dosage, only: :index, path: "/gene-dosage"
  resources :gene_disease_assertions, only: [:show, :index], path: "/gene-validity"
  resources :actionability_assertions, only: [:show, :index], path: "/actionability"
  resources :home, only: [:show, :index]
  resources :phenotypes, only: [:index]

  resources :affiliates, only: [:show, :index, :all] do
    member do
      get 'all'
    end
  end


  # Items that need to be secured
  authenticate :agent do
    resources :subscriptions
    resources :notes
    resources :dashboard, only: [:index]  #should only be registered agents
  end


  # TODO refine routes later, for now want routes for
  # disease, conditions, and phenotypes
  # resources :diseases
  resources :conditions
  # no phenotypes yet, but soon!
  # resources :phenotypes

  devise_for :agents

  root to: 'home#index'
end

app/helpers/external_resources_helper.rb
module ExternalResourcesHelper
end

app/views/external_resources/gene.html.erb
<div id="genes_show" class="container">
  
</div>
<div id="genes_show_summary" role="tabpanel" class="tab-pane active  container results_curation_summary">
  <div class="row">
    <div class="col-sm-12">
      <h2 class="padding-top-xs">
        <%= render 'shared/agent_links_show_views' %>

        <strong><%= @gene.symbol %></strong> Gene Summary
        </h2>
        <%= render 'genes/gene_facts' %>

      </div>
    </div>
    <div class="col-sm-12">
      <div class="">
        <ul class="nav nav-tabs">        
          <li>
	            <%= link_to gene_path(@gene), :class => ""  do %>
	        ClinGen's <%= @gene.symbol %> Curation Summaries
	      <% end %>
          </li> 
          <!-- <li class="">
            <a href="#variants">
              ClinVar Variants <span class="badge">#####</span>
            </a>
          </li> -->
          <li class="active">
            <%= link_to "External Genomic Resources", gene_external_resources_path(@gene) %>
          </li>
        </ul>
        <div class="panel panel-default">
          <div class="panel-heading" id='results_curation_summary_heading'>
            <div class="row">
            	<div class="col-sm-12">
	              External Resources
	            </div>
	          </div>
          </div>
          <div id='results_curation_summary_details' class="panel-body results_curation_summary_details">
            dsdfsdfdsfdsf
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/external_resources/index.html.erb
<div id="genes_show" class="container">
  
</div>
<div id="genes_show_summary" role="tabpanel" class="tab-pane active  container results_curation_summary">
  <div class="row">
    <div class="col-sm-12">

        <%= render 'genes/gene_facts' %>

      </div>
    </div>
    <div class="col-sm-12">
      <div class="">
        <ul class="nav nav-tabs">        
          <li>
	            <%= link_to gene_path(@gene), :class => ""  do %>
	        ClinGen's <%= @gene.symbol %> Curation Summaries
	      <% end %>
          </li> 
          <!-- <li class="">
            <a href="#variants">
              ClinVar Variants <span class="badge">#####</span>
            </a>
          </li> -->
          <li class="active">
            <%= link_to "External Genomic Resources", gene_external_resources_path(@gene) %>
          </li>
        </ul>
        <div class="panel panel-default">
          <div class="panel-heading" id='results_curation_summary_heading'>
            <div class="row">
            	<div class="col-sm-12">
	              External Resources
	            </div>
	          </div>
          </div>
          <div id='results_curation_summary_details' class="panel-body results_curation_summary_details">
            dsdfsdfdsfdsf

            <%= gene_medgen_genetics_summary("link", @gene.symbol) %><br>
            <%= gene_genetic_practice_guidelines("link", @gene.symbol) %><br>
            <%= gene_omim("link", @gene.symbol) %><br>
            <%= gene_genetics_home_reference("link", @gene.symbol) %><br>
            <%= gene_gene_reviews("link", @gene.symbol) %><br>
            <%= gene_clinvar("link", @gene.symbol) %><br>
            <%= gene_clinvar_acmg_variants("link", @gene.symbol) %><br>
            <%= gene_1000_enomes("link", @gene.symbol) %><br>
            <%= gene_ncbi_browser("link", @gene.symbol) %><br>
            <hr />
            <%= condition_gtr_disease_tests("link", @gene.symbol) %><br>
            <%= condition_genetic_practice_guidelines("link", @gene.symbol) %><br>
            <%= condition_omim("link", @gene.symbol) %><br>
            <%= condition_pharmgkb("link", @gene.symbol) %><br>
            <%= condition_medgen_genetic_summary("link", @gene.symbol) %><br>
            <%= condition_genetics_home_reference("link", @gene.symbol) %><br>
            <%= condition_clinvar_variants_related_to_genetic_disease("link", @gene.symbol) %><br>
            <%= condition_1000_genomes("link", @gene.symbol) %><br>
            <hr />
            <%= drug_pharmgkb_dosing_guidelines("link", @gene.symbol) %><br>
            <%= drug_gtr_clia("link", @gene.symbol) %><br>
            <%= drug_cpic_pharmacogenomics_guidelines("link", @gene.symbol) %><br>
            <%= drug_medgen_drug_gene_summary("link", @gene.symbol) %><br>
            <%= drug_genetic_practice_guidelines("link", @gene.symbol) %><br>
            <%= drug_omim("link", @gene.symbol) %><br>
            <%= drug_clinvar_variants_with_drug_response("link", @gene.symbol) %><br>
            <%= drug_clinvar_medication_ingredient("link", @gene.symbol) %><br>
            <%= drug_1000_genomes_general_medication("link", @gene.symbol) %><br>
            <%= gene_gtr_gene_tests("link", @gene.symbol) %><br>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>